// 4.UI/3-Angular/router-demo/src/app/product-form/product-form.component.ts
import { FormBuilder, FormGroup } from '@angular/forms';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-product-form',
  templateUrl: './product-form.component.html',
  styleUrls: ['./product-form.component.css']
})
export class ProductFormComponent implements OnInit {

  productForm:FormGroup;
  constructor(private fb:FormBuilder) { }

  ngOnInit() {
    this.productForm=this.fb.group(
      {
        id:[0,[]],
        name:['',[]],
        price:[0.0,[]],
        description:['',[]]
     })
  }

}

<div class='card'>
  <div class='card-header'>Products</div>
  <div class='card-body'>
    <form [formGroup]="productForm">

      <div class='form-group'>
        <label>ID</label>
        <input type="text" class='form-control' formControlName="id">
      </div>

      <div class='form-group'>
        <label>Name</label>
        <input type="text" class='form-control' formControlName="name">
      </div>
      <div class='form-group'>
        <label>Price</label>
        <input type="text" class='form-control' formControlName="price">
      </div>
      <div class='form-group'>
        <label>Description</label>
        <textarea class='form-control' formControlName="description"></textarea>
      </div>

      <div class='text-center'>
        <button class='btn btn-outline-dark'>Submit</button>
      </div>

    </form>
  </div>
</div>

// 4.UI/4-React/Product-APP-v1/src/components/ProductForm.js
import React, { Component } from 'react';

class ProductForm extends Component {

    handleForm(e) {
        e.preventDefault();
        let newProduct = {
            name: this.refs.name.value,
            price: this.refs.price.value
        }
       // console.log(newProduct);

        let {onFormSubmit}=this.props;
        if(onFormSubmit){
            onFormSubmit(newProduct);
        }

    }
    render() {
        return (
            <div>
                <div className="card">
                    <div className="card-header bg-primary">Product-Form</div>
                    <div className="card-body">

                        <div className="row">
                            <div className="col-6 col-md-6 col-lg-6">

                                <form onSubmit={e => this.handleForm(e)}>
                                    <div className="form-group">
                                        <label>Name</label>
                                        <input type="text" className="form-control" ref="name" />
                                    </div>
                                    <div className="form-group">
                                        <label>Price</label>
                                        <input type="text" className="form-control" ref="price" />
                                    </div>
                                    <button className="btn btn-primary">Submit</button>

                                </form>

                            </div>
                        </div>

                    </div>

                </div>

            </div>
        );
    }
}

export default ProductForm;
